#ifndef NX3D_ERROR_H
#define NX3D_ERROR_H

#define NX3D_ERROR_NONE                 0
#define NX3D_ERROR_NOT_IMPLEMENTED      1
#define NX3D_ERROR_OUT_OF_MEMORY        2
#define NX3D_ERROR_ALREADY_INITIALIZED  3
#define NX3D_ERROR_NOT_INITIALIZED      4
#define NX3D_ERROR_PBKIT_INIT_FAILED    5
#define NX3D_ERROR_INVALID_ARGUMENT     6
#define NX3D_ERROR_INVALID_OPERATION    7

#endif
